# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bosco <bosco@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/27 20:10:54 by bosco             #+#    #+#              #
#    Updated: 2024/10/27 20:42:22 by bosco            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libftprintf.a
CC = CC
CCFLAGS = -Wall -Wextra -Werror

SRC = ft_print.c

OBJ = $(SRC:.c=.o)

LIBFT_PATH = ./libft